# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

fastlane_version '2.140.0'

#before_all do
#  ensure_git_branch
#  ensure_git_status_clean
#  git_pull
#end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    increment_build_number(xcodeproj: "./ios/sylk.xcodeproj")

    build_app(export_xcargs: "-allowProvisioningUpdates", workspace: "./ios/sylk.xcworkspace", scheme: "sylk")

    upload_to_testflight

  end
end

platform :android do
  desc "Push a new beta build to Google Play Store"
  lane :beta do

    gradle(task: 'clean', project_dir: "android/") # <- Fixes it

    next_version_code = increment_version_code(
      app_project_dir: '**/app',
      version_code: File.read("../android/VERSION_CODE")
    )
    UI.message(next_version_code)
    set_value_in_build(
      key: 'versionCode',
      value: next_version_code
    )

    next_version_name = increment_version_name(
      app_project_dir: '**/app',
      bump_type: 'major',
      version_name: File.read("../android/VERSION_NAME")
    )
    UI.message(next_version_name)
    set_value_in_build(
      key: 'versionName',
      value: next_version_name
    )

    gradle(task: 'bundle', build_type: 'Release', project_dir: './android/', properties: {
      "android.enableJetifier" => "true",
      "android.useAndroidX" => "true"
    })

    upload_to_play_store(track: 'beta', package_name: 'com.agprojects.sylk', skip_upload_apk: true, timeout: 5000)

  end
end
